name: Create Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue Title'
        required: true
      body:
        description: 'Issue Body'
        required: true

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-or-update-issue@v2
        with:
          title: ${{ github.event.inputs.title }}
          body: ${{ github.event.inputs.body }}
          token: ${{ secrets.TOKEN }}
