name: API

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue Title'
        required: true
      body:
        description: 'Issue Body'
        required: true

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hotcake123/hotcake123-test/issues \
          -d '{"title": "${{ github.event.inputs.title }}", "body": "${{ github.event.inputs.body }}"}'
